<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ToySeeder extends Seeder
{
    public function run()
    {
        DB::table('toys')->insert([
            [
                'toy_id' => Str::uuid(),
                'category_id' => Str::uuid(), // Sesuaikan dengan category_id yang ada
                'image' => 'path/to/lego.jpg',
                'name' => 'Lego',
                'description' => 'A popular building toy.',
                'stock' => 100,
                'price' => 2000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'toy_id' => Str::uuid(),
                'category_id' => Str::uuid(),
                'image' => 'path/to/robot.jpg',
                'name' => 'Robot',
                'description' => 'An interactive robot toy.',
                'stock' => 50,
                'price' => 5000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'toy_id' => Str::uuid(),
                'category_id' => Str::uuid(),
                'image' => 'path/to/car.jpg',
                'name' => 'Car',
                'description' => 'A remote control car.',
                'stock' => 70,
                'price' => 1500,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'toy_id' => Str::uuid(),
                'category_id' => Str::uuid(),
                'image' => 'path/to/building_blocks.jpg',
                'name' => 'Building Blocks',
                'description' => 'Colorful building blocks.',
                'stock' => 120,
                'price' => 2500,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'toy_id' => Str::uuid(),
                'category_id' => Str::uuid(),
                'image' => 'path/to/card_game.jpg',
                'name' => 'Card Games',
                'description' => 'Exciting card games for all ages.',
                'stock' => 80,
                'price' => 1000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'toy_id' => Str::uuid(),
                'category_id' => Str::uuid(),
                'image' => 'path/to/teddy_bear.jpg',
                'name' => 'Teddy Bear',
                'description' => 'A cuddly teddy bear.',
                'stock' => 60,
                'price' => 2500,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'toy_id' => Str::uuid(),
                'category_id' => Str::uuid(),
                'image' => 'path/to/stickers.jpg',
                'name' => 'Stickers',
                'description' => 'A set of fun stickers.',
                'stock' => 150,
                'price' => 500,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'toy_id' => Str::uuid(),
                'category_id' => Str::uuid(),
                'image' => 'path/to/dolls.jpg',
                'name' => 'Dolls',
                'description' => 'A set of beautiful dolls.',
                'stock' => 40,
                'price' => 3000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'toy_id' => Str::uuid(),
                'category_id' => Str::uuid(),
                'image' => 'path/to/tea_set.jpg',
                'name' => 'Tea Set',
                'description' => 'A toy tea set for kids.',
                'stock' => 30,
                'price' => 2000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'toy_id' => Str::uuid(),
                'category_id' => Str::uuid(),
                'image' => 'path/to/beyblade.jpg',
                'name' => 'Beyblade',
                'description' => 'A popular spinning top toy.',
                'stock' => 90,
                'price' => 1500,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'toy_id' => Str::uuid(),
                'category_id' => Str::uuid(),
                'image' => 'path/to/jigsaw_puzzle.jpg',
                'name' => 'Jigsaw Puzzle',
                'description' => 'A challenging jigsaw puzzle.',
                'stock' => 70,
                'price' => 1000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'toy_id' => Str::uuid(),
                'category_id' => Str::uuid(),
                'image' => 'path/to/transformers.jpg',
                'name' => 'Transformers',
                'description' => 'A set of Transformers action figures.',
                'stock' => 50,
                'price' => 3500,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'toy_id' => Str::uuid(),
                'category_id' => Str::uuid(),
                'image' => 'path/to/play_doh.jpg',
                'name' => 'Play-Doh',
                'description' => 'Colorful Play-Doh for creative play.',
                'stock' => 100,
                'price' => 1200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'toy_id' => Str::uuid(),
                'category_id' => Str::uuid(),
                'image' => 'path/to/dominoes.jpg',
                'name' => 'Dominoes',
                'description' => 'A classic dominoes set.',
                'stock' => 80,
                'price' => 1000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'toy_id' => Str::uuid(),
                'category_id' => Str::uuid(),
                'image' => 'path/to/slinky.jpg',
                'name' => 'Slinky',
                'description' => 'A fun slinky toy.',
                'stock' => 110,
                'price' => 800,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
